import { HomeBlockModule } from '@libs/api/feature-home-block';
import { ImageModule } from '@libs/api/feature-image';
import { ProductModule } from '@libs/api/feature-product';
import { ProductCategoryModule } from '@libs/api/feature-product-category';
import { ProductLengthModule } from '@libs/api/feature-product-length';
import { UserModule } from '@libs/api/feature-user';
import { Module, ValidationPipe } from '@nestjs/common';
import { APP_PIPE } from '@nestjs/core';
import { GraphQLModule } from '@nestjs/graphql';
import { MercuriusDriver, MercuriusDriverConfig } from '@nestjs/mercurius';
import * as path from 'node:path';

const validationProvider = {
  provide: APP_PIPE,
  useValue: new ValidationPipe()
};

@Module({
  imports: [
    GraphQLModule.forRoot<MercuriusDriverConfig>({
      driver: MercuriusDriver,
      graphiql: true,
      // eslint-disable-next-line unicorn/prefer-module
      autoSchemaFile: path.join(__dirname, './autogenerated-schema.gql')
    }),
    UserModule,
    HomeBlockModule,
    ImageModule,
    ProductModule,
    ProductCategoryModule,
    ProductLengthModule
  ],
  providers: [validationProvider]
})
export class AppModule {}
