import '../styles/global.css';

import { ClerkProvider } from '@clerk/nextjs';
import { Lato } from 'next/font/google';

// not use because "Error [NextFontError]: Failed to fetch `Inter` from Google Fonts." happend.
// import { Inter } from 'next/font/google';
// const inter = Inter({ subsets: ['latin'] });

const lato = Lato({
  weight: ['400', '700'],
  display: 'swap',
  style: 'normal',
  subsets: ['latin']
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={lato.className}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
